### ISSUE TITLE
Helpline Section 

### ISSUE THREAD

**Issue by Isha307** [GDSC-IIIT-Kalyani/RAKSHA#2]
Add the **helpline section** where safety guidelines and helpline numbers is present.

**Comment by ayushi25jaiswal** [comment]
Hi, I think I understand the task and can solve it so if possible can you assign this to me.

**Comment by Isha307** [comment]
@ayushi25jaiswal Assigned to you, Try to make the PR soon :)

**Comment by ayushi25jaiswal** [comment]
please review my PR.
