### ISSUE TITLE
Chatbot feature

### ISSUE THREAD

**Issue by Isha307** [GDSC-IIIT-Kalyani/RAKSHA#3]
Add the chatbot to help the users.

**Comment by ayushi25jaiswal** [comment]
I will love to work on this feature. It will be good, if you can assign it to me.

**Comment by ayushi25jaiswal** [comment]
I have submitted PR can you please review it.

**Comment by ayushi25jaiswal** [comment]
Extremely sorry for that, I have created new PR can you please again review it.
